---
- hosts: all
  become: yes
  vars:
    fixpack_filename: "9.2.0-IBM-MQ-LinuxX64-FP00{{ fixpack_version }}.tar.gz"
  roles:
    - check-limit
    - install-boto
    - transfer-fixpack
    - stop-miqm
    - install-fp
    - start-miqm
    - balance-miqm