---
- name: Transfer the fixpack file to the server
  shell:
    cmd: |
      /usr/local/bin/aws s3 cp {{ s3-url }}{{ fixpack_filename }} /mq/Fixpack/

- name: Untar FIXPACK and update
  shell: "cd /mq/Fixpack; tar xvfz {{ fixpack_filename }}"